server:
  port: 8001

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: -1 # 最大连接数, 负值无限制
        max-idle: 10 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
    timeout: 1000 # 连接超时时间(毫秒)
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
      username:
      password:
      connection-timeout: 5
      read-timeout: 60